export const PRESALE_TOKEN_DECIMALS = 5;
export const PRESALE_PROGRAM_ID = "4yBTZXsuz7c1X3PJF4PPCJr8G6HnNAgRvzAWVoFZMncH";
export const PRESALE_TOKEN_MINT = "9e4U5CwGXaAf8d1XipoWNn2V6U7h4BM8UpYNdDkPkP6G";
export const PRESALE_OWNER_PUB_KEY = "56soKhmhDDx9A4BUqVZmr7ENqBxroFZmtrNTzw47S5Dr";
export const PRESALE_STATE_ACCOUNT_PUB_KEY = "G7RSwCQeJVRkgPspTXu2PQLGA3134p6SyMnPj6Wuwmue";
export const PRESALE_TOKEN_ACCOUNT_PUB_KEY = "Csjw6CJo9MKA9GYrsxVm1tEogEqTtRK6oemCdjzmVhPg";
export const TOKEN_PRICE_PER_SOL = 90000;
export const SOLANA_CONNECTION_URL = "http://127.0.0.1:8899";